import logging
import re
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Dict, List, Optional, Pattern, Tuple

from ai_content_classifier.core.logger import LoggableMixin


@dataclass
class CategoryExtractionConfig:
    """
    Configuration class for category extraction patterns and settings.

    This class centralizes all the regex patterns and settings used for
    extracting categories from LLM responses, making them easily configurable
    and maintainable.
    """

    # Explicit statement patterns (Category: X, The category is X, etc.)
    explicit_patterns: List[str] = field(
        default_factory=lambda: [
            r"(?:the\s+)?(?:category|classification|class|label|topic|subject)(?:\s+is|\s+would\s+be)?:\s*([a-zA-Z0-9\s]+)",
            r"(?:this|it|the\s+content)\s+(?:is|belongs|falls\s+under|fits\s+in)(?:\s+the\s+category\s+of|\s+in\s+the\s+category\s+of)?\s+(?:the\s+)?([a-zA-Z0-9\s]+)(?:\s+category)?",
            r"(?:i\s+would|we\s+can|we\s+should)\s+(?:classify|categorize|label|consider)\s+this\s+as\s+(?:a\s+)?([a-zA-Z0-9\s]+)",
            r"(?:best|most\s+appropriate)\s+(?:category|classification)\s+(?:is|would\s+be)(?:\s+the)?\s+([a-zA-Z0-9\s]+)",
        ]
    )

    # Emphasis patterns (**Category**, *Category*, "Category")
    emphasis_patterns: List[str] = field(
        default_factory=lambda: [
            r"\*\*([^*]+)\*\*",  # Bold: **text**
            r"\*([^*]+)\*",  # Italic: *text*
            r'"([^"]+)"',  # Quotes: "text"
            r"'([^']+)'",  # Single quotes: 'text'
        ]
    )

    # Positive context patterns
    positive_context_patterns: List[str] = field(
        default_factory=lambda: [
            r"(?:this|it|the\s+document|the\s+content|the\s+text|the\s+image)\s+(?:is|appears\s+to\s+be|looks\s+like)\s+(?:a|an)?\s+(\w+)",
            r"(?:clearly|obviously|definitely|certainly)\s+(?:is|belongs\s+to|falls\s+under)\s+(?:the)?\s+(\w+)",
            r"(?:best|most\s+appropriate)\s+(?:match|fit|category)\s+(?:would\s+be|is)\s+(\w+)",
            r"(?:i\s+would|i\s+believe|i\s+think)\s+(?:this|it)\s+(?:is|falls\s+into)\s+(?:the)?\s+(\w+)",
        ]
    )

    # Negative context patterns (to exclude categories mentioned negatively)
    negative_patterns: List[str] = field(
        default_factory=lambda: [
            r"not\s+(?:a|an)?\s+(\w+)",
            r"isn't\s+(?:a|an)?\s+(\w+)",
            r"doesn't\s+(?:concern|relate\s+to)\s+(\w+)",
            r"(?:this|it)\s+is\s+not\s+(?:about|related\s+to)\s+(\w+)",
            r"(?:nor)\s+(?:is\s+it|does\s+it)\s+(?:about|related\s+to)\s+(\w+)",
            r"never\s+(?:a|an)?\s+(\w+)",
            r"far\s+from\s+(?:a|an)?\s+(\w+)",
            r"anything\s+but\s+(?:a|an)?\s+(\w+)",
            r"rather\s+than\s+(?:a|an)?\s+(\w+)",
            r"(?:can't|cannot)\s+be\s+(?:considered|classified|categorized)\s+(?:as)?\s+(\w+)",
            r"wouldn't\s+(?:consider|classify|categorize)\s+(?:as|it\s+as)?\s+(\w+)",
            r"should\s+not\s+be\s+(?:considered|classified|categorized)\s+(?:as)?\s+(\w+)",
            r"no\s+(\w+)\s+(?:elements|content|aspects)",
            r"(?:definitely|absolutely|certainly|clearly)\s+not\s+(\w+)",
            r"while\s+(?:it'?s|it\s+is)\s+not\s+(\w+)",
            r"it'?s\s+(?:definitely|absolutely|certainly|clearly)?\s+not\s+(\w+)",
        ]
    )

    # Minimum confidence score for category extraction
    min_confidence_score: float = 0.3

    # Maximum length for extracted category text
    max_category_length: int = 50


@dataclass
class CategoryExtractionResult:
    """
    Result of category extraction with confidence score and method used.
    """

    category: str
    confidence: float
    method: str
    details: str = ""


class CategoryAnalyzer(LoggableMixin):
    """
    Analyzer for extracting category information from LLM response text.

    This class provides methods to parse and extract category labels from
    response text generated by language models. It uses multiple strategies
    with configurable patterns and provides confidence scoring.
    """

    def __init__(
        self,
        config: Optional[CategoryExtractionConfig] = None,
        log_level: int = logging.INFO,
    ):
        """
        Initialize the category analyzer with a logger and configuration.

        Args:
            config: Configuration for extraction patterns and settings
            log_level: The logging level to use (default: logging.INFO)
        """
        self.__init_logger__(log_level)
        self.config = config or CategoryExtractionConfig()

        # Cache for compiled regex patterns
        self._compiled_patterns: Dict[str, List[Pattern]] = {}
        self._compile_patterns()

    def _compile_patterns(self) -> None:
        """
        Compile all regex patterns for better performance.
        This method is called once during initialization.
        """
        self.logger.debug("Compiling regex patterns for category extraction")

        pattern_groups = {
            "explicit": self.config.explicit_patterns,
            "emphasis": self.config.emphasis_patterns,
            "positive_context": self.config.positive_context_patterns,
            "negative": self.config.negative_patterns,
        }

        for group_name, patterns in pattern_groups.items():
            compiled = []
            for pattern in patterns:
                try:
                    compiled.append(re.compile(pattern, re.IGNORECASE))
                except re.error as e:
                    self.logger.warning(
                        f"Invalid regex pattern in {group_name}: {pattern} - {e}"
                    )

            self._compiled_patterns[group_name] = compiled
            self.logger.debug(f"Compiled {len(compiled)} patterns for {group_name}")

    def extract_category_with_confidence(
        self, response_text: str, available_categories: List[str]
    ) -> CategoryExtractionResult:
        """
        Extract category with confidence score and detailed information.

        Args:
            response_text: The response text from the LLM
            available_categories: List of valid category names

        Returns:
            CategoryExtractionResult: Detailed extraction result with confidence
        """
        # Input validation
        if not self._validate_inputs(response_text, available_categories):
            return CategoryExtractionResult(
                category="unknown",
                confidence=0.0,
                method="validation_failed",
                details="Invalid input parameters",
            )

        self.logger.debug(
            f"Extracting category from response ({len(response_text)} chars)"
        )

        # Normalize inputs for processing
        normalized_text = response_text.lower().strip()
        normalized_categories = [cat.lower().strip() for cat in available_categories]

        # Try extraction strategies in order of reliability
        extraction_strategies = [
            ("explicit_statement", self._extract_by_explicit_statement),
            ("emphasis", self._extract_by_emphasis),
            ("positive_context", self._extract_by_positive_context),
            ("frequency_analysis", self._extract_by_frequency_analysis),
        ]

        for method_name, strategy_func in extraction_strategies:
            try:
                result = strategy_func(
                    normalized_text, normalized_categories, available_categories
                )
                if result and result.confidence >= self.config.min_confidence_score:
                    self.logger.info(
                        f"Category extracted using {method_name}: {result.category} (confidence: {result.confidence:.2f})"
                    )
                    return result
                elif result:
                    self.logger.debug(
                        f"Low confidence result from {method_name}: {result.category} (confidence: {result.confidence:.2f})"
                    )
            except Exception as e:
                self.logger.error(
                    f"Error in extraction strategy {method_name}: {str(e)}",
                    exc_info=True,
                )

        # If all strategies fail
        self.logger.warning(
            "Could not determine category from response with sufficient confidence"
        )
        return CategoryExtractionResult(
            category="unknown",
            confidence=0.0,
            method="all_strategies_failed",
            details="No strategy yielded confident results",
        )

    def _validate_inputs(
        self, response_text: str, available_categories: List[str]
    ) -> bool:
        """
        Validate input parameters for category extraction.

        Args:
            response_text: The response text to validate
            available_categories: The categories list to validate

        Returns:
            bool: True if inputs are valid, False otherwise
        """
        if not response_text or not isinstance(response_text, str):
            self.logger.warning("Invalid response_text: empty or non-string")
            return False

        if not available_categories or not isinstance(available_categories, list):
            self.logger.warning("Invalid available_categories: empty or non-list")
            return False

        if not all(
            isinstance(cat, str) and cat.strip() for cat in available_categories
        ):
            self.logger.warning(
                "Invalid categories: contains non-string or empty categories"
            )
            return False

        return True

    def _extract_by_explicit_statement(
        self,
        normalized_text: str,
        normalized_categories: List[str],
        original_categories: List[str],
    ) -> Optional[CategoryExtractionResult]:
        """
        Extract category from explicit statements using compiled patterns.

        Returns:
            Optional[CategoryExtractionResult]: Extraction result or None if not found
        """
        patterns = self._compiled_patterns.get("explicit", [])

        for pattern in patterns:
            matches = pattern.finditer(normalized_text)
            for match in matches:
                extracted = match.group(1).strip()

                # Clean and validate extracted text
                if not self._is_valid_extracted_text(extracted):
                    continue

                category_result = self._match_extracted_to_categories(
                    extracted, tuple(normalized_categories), tuple(original_categories)
                )

                if category_result:
                    confidence = self._calculate_explicit_confidence(
                        match, normalized_text
                    )
                    return CategoryExtractionResult(
                        category=category_result,
                        confidence=confidence,
                        method="explicit_statement",
                        details=f"Pattern: {pattern.pattern}, Match: '{extracted}'",
                    )

        return None

    def _extract_by_emphasis(
        self,
        normalized_text: str,
        normalized_categories: List[str],
        original_categories: List[str],
    ) -> Optional[CategoryExtractionResult]:
        """
        Extract category based on text emphasis using compiled patterns.

        Returns:
            Optional[CategoryExtractionResult]: Extraction result or None if not found
        """
        patterns = self._compiled_patterns.get("emphasis", [])

        # Check first line first (higher confidence)
        first_line = (
            normalized_text.split("\n")[0]
            if "\n" in normalized_text
            else normalized_text
        )

        for check_text, confidence_multiplier in [
            (first_line, 1.2),
            (normalized_text, 1.0),
        ]:
            for pattern in patterns:
                matches = pattern.finditer(check_text)
                for match in matches:
                    emphasized_text = match.group(1).strip()

                    if not self._is_valid_extracted_text(emphasized_text):
                        continue

                    category_result = self._match_extracted_to_categories(
                        emphasized_text,
                        tuple(normalized_categories),
                        tuple(original_categories),
                    )

                    if category_result:
                        base_confidence = 0.7 if check_text == first_line else 0.6
                        confidence = min(0.95, base_confidence * confidence_multiplier)

                        return CategoryExtractionResult(
                            category=category_result,
                            confidence=confidence,
                            method="emphasis",
                            details=f"Emphasized text: '{emphasized_text}', Location: {'first_line' if check_text == first_line else 'full_text'}",
                        )

        return None

    def _extract_by_positive_context(
        self,
        normalized_text: str,
        normalized_categories: List[str],
        original_categories: List[str],
    ) -> Optional[CategoryExtractionResult]:
        """
        Extract category based on positive contextual clues.

        Returns:
            Optional[CategoryExtractionResult]: Extraction result or None if not found
        """
        patterns = self._compiled_patterns.get("positive_context", [])
        negative_patterns = self._compiled_patterns.get("negative", [])

        # First, identify categories mentioned in negative contexts
        negative_categories = self._find_negative_mentions(
            normalized_text, negative_patterns, normalized_categories
        )

        # Look for positive mentions
        for pattern in patterns:
            matches = pattern.finditer(normalized_text)
            for match in matches:
                context_word = match.group(1).strip()

                if not self._is_valid_extracted_text(context_word):
                    continue

                category_result = self._match_extracted_to_categories(
                    context_word,
                    tuple(normalized_categories),
                    tuple(original_categories),
                )

                if (
                    category_result
                    and category_result.lower() not in negative_categories
                ):
                    confidence = 0.6
                    return CategoryExtractionResult(
                        category=category_result,
                        confidence=confidence,
                        method="positive_context",
                        details=f"Context word: '{context_word}', Pattern: {pattern.pattern}",
                    )

        # Check for single remaining category not mentioned negatively
        remaining_categories = [
            (original_categories[i], cat)
            for i, cat in enumerate(normalized_categories)
            if cat not in negative_categories and cat in normalized_text
        ]

        if len(remaining_categories) == 1:
            confidence = 0.5
            return CategoryExtractionResult(
                category=remaining_categories[0][0],
                confidence=confidence,
                method="positive_context",
                details="Single non-negated category found",
            )

        return None

    def _extract_by_frequency_analysis(
        self,
        normalized_text: str,
        normalized_categories: List[str],
        original_categories: List[str],
    ) -> Optional[CategoryExtractionResult]:
        """
        Extract category based on frequency analysis, excluding negative mentions.

        Returns:
            Optional[CategoryExtractionResult]: Extraction result or None if not found
        """
        negative_patterns = self._compiled_patterns.get("negative", [])
        negative_spans = self._get_negative_spans(normalized_text, negative_patterns)

        frequency_scores = {}

        # Count frequency of each category, avoiding negative contexts
        for i, category in enumerate(normalized_categories):
            score = 0

            if " " not in category:
                # Single-word categories: find whole-word matches
                pattern = re.compile(r"\b" + re.escape(category) + r"\b")
                matches = pattern.finditer(normalized_text)

                for match in matches:
                    if not self._is_in_negative_context(match.span(), negative_spans):
                        score += 1
            else:
                # Multi-word categories: check for phrase occurrence
                count = normalized_text.count(category)
                # Simple heuristic: assume half are in negative context
                score = max(0, count - count // 2)

            frequency_scores[original_categories[i]] = score

        # Find category with highest frequency
        if frequency_scores:
            max_category = max(frequency_scores.items(), key=lambda x: x[1])
            max_score = max_category[1]

            if max_score > 0:
                # Calculate confidence based on frequency and dominance
                total_mentions = sum(frequency_scores.values())
                confidence = min(0.5, (max_score / max(total_mentions, 1)) * 0.5 + 0.2)

                return CategoryExtractionResult(
                    category=max_category[0],
                    confidence=confidence,
                    method="frequency_analysis",
                    details=f"Frequency: {max_score}, Total mentions: {total_mentions}",
                )

        return None

    @lru_cache(maxsize=128)
    def _match_extracted_to_categories(
        self,
        extracted: str,
        normalized_categories_tuple: Tuple[str, ...],
        original_categories_tuple: Tuple[str, ...],
    ) -> Optional[str]:
        """
        Match extracted text to available categories with caching.

        Args:
            extracted: The extracted text to match
            normalized_categories_tuple: Tuple of normalized category names (for caching)
            original_categories_tuple: Tuple of original category names (for caching)

        Returns:
            Optional[str]: Matched category or None
        """
        normalized_categories = list(normalized_categories_tuple)
        original_categories = list(original_categories_tuple)

        clean_extracted = re.sub(r"[^\w\s]", "", extracted).strip()

        # Direct match
        if clean_extracted in normalized_categories:
            idx = normalized_categories.index(clean_extracted)
            return original_categories[idx]

        # Match with "category" suffix
        category_variant = f"{clean_extracted} category"
        if category_variant in [cat + " category" for cat in normalized_categories]:
            for i, cat in enumerate(normalized_categories):
                if f"{cat} category" == category_variant:
                    return original_categories[i]

        # Multi-word category match
        for i, category in enumerate(normalized_categories):
            if " " in category:
                words_in_category = category.split()
                if all(word in clean_extracted for word in words_in_category):
                    return original_categories[i]

        return None

    def _find_negative_mentions(
        self,
        text: str,
        negative_patterns: List[Pattern],
        normalized_categories: List[str],
    ) -> set:
        """
        Find categories mentioned in negative contexts.

        Returns:
            set: Set of category names mentioned negatively
        """
        negative_categories = set()

        for pattern in negative_patterns:
            matches = pattern.finditer(text)
            for match in matches:
                negative_word = match.group(1).strip()

                for category in normalized_categories:
                    if category == negative_word or (
                        len(category.split()) == 1 and negative_word in category
                    ):
                        negative_categories.add(category)

        return negative_categories

    def _get_negative_spans(
        self, text: str, negative_patterns: List[Pattern]
    ) -> List[Tuple[int, int]]:
        """
        Get text spans that contain negative mentions.

        Returns:
            List[Tuple[int, int]]: List of (start, end) spans for negative contexts
        """
        negative_spans = []

        for pattern in negative_patterns:
            matches = pattern.finditer(text)
            for match in matches:
                negative_spans.append(match.span())

        return negative_spans

    def _is_in_negative_context(
        self, span: Tuple[int, int], negative_spans: List[Tuple[int, int]]
    ) -> bool:
        """
        Check if a text span overlaps with any negative context span.

        Returns:
            bool: True if the span is in negative context
        """
        start, end = span

        for neg_start, neg_end in negative_spans:
            if start >= neg_start and end <= neg_end:
                return True

        return False

    def _is_valid_extracted_text(self, text: str) -> bool:
        """
        Validate extracted text for basic sanity checks.

        Returns:
            bool: True if text is valid for category matching
        """
        if not text or len(text) > self.config.max_category_length:
            return False

        # Check if text contains only reasonable characters
        if not re.match(r"^[a-zA-Z0-9\s\-_]+$", text):
            return False

        return True

    def _calculate_explicit_confidence(self, match: re.Match, full_text: str) -> float:
        """
        Calculate confidence score for explicit pattern matches.

        Returns:
            float: Confidence score between 0.0 and 1.0
        """
        base_confidence = 0.8

        # Boost confidence if match is at the beginning of the text
        if match.start() < len(full_text) * 0.1:
            base_confidence += 0.1

        # Boost confidence for certain keywords
        match_text = match.group(0).lower()
        if any(
            keyword in match_text
            for keyword in ["category is", "classified as", "belongs to"]
        ):
            base_confidence += 0.05

        return min(0.95, base_confidence)

    def get_extraction_statistics(
        self, response_text: str, available_categories: List[str]
    ) -> Dict[str, any]:
        """
        Get detailed statistics about the extraction process.

        Args:
            response_text: The response text to analyze
            available_categories: List of available categories

        Returns:
            Dict: Statistics including pattern matches, confidence scores, etc.
        """
        if not self._validate_inputs(response_text, available_categories):
            return {"error": "Invalid inputs"}

        normalized_text = response_text.lower().strip()
        normalized_categories = [cat.lower().strip() for cat in available_categories]

        stats = {
            "text_length": len(response_text),
            "normalized_text_length": len(normalized_text),
            "available_categories": len(available_categories),
            "pattern_matches": {},
            "negative_mentions": [],
            "category_frequencies": {},
        }

        # Check pattern matches
        for pattern_type, patterns in self._compiled_patterns.items():
            matches = []
            for pattern in patterns:
                for match in pattern.finditer(normalized_text):
                    matches.append(
                        {
                            "pattern": pattern.pattern,
                            "match": match.group(0),
                            "span": match.span(),
                        }
                    )
            stats["pattern_matches"][pattern_type] = matches

        # Calculate category frequencies
        negative_patterns = self._compiled_patterns.get("negative", [])
        negative_spans = self._get_negative_spans(normalized_text, negative_patterns)

        for category in normalized_categories:
            count = 0
            if " " not in category:
                pattern = re.compile(r"\b" + re.escape(category) + r"\b")
                matches = pattern.finditer(normalized_text)
                for match in matches:
                    if not self._is_in_negative_context(match.span(), negative_spans):
                        count += 1
            else:
                count = normalized_text.count(category)

            stats["category_frequencies"][category] = count

        # Find negative mentions
        negative_categories = self._find_negative_mentions(
            normalized_text, negative_patterns, normalized_categories
        )
        stats["negative_mentions"] = list(negative_categories)

        return stats
